### ISSUE TITLE
Errors w/ sleep on Mac popped up again

### ISSUE THREAD

**Issue by ctheune** [freifunkMUC/jitsi-meet-electron#2]
I know you fixed something around this, but @zagy just got this on 2.0.4:

```
Uncaught Exception:
Error: Object has been destroyed
    at PowerMonitor.<anonymous> (/Applications/FreifunkMeet.app/Contents/Resources/app.asar/node_modules/jitsi-meet-electron-utils/powermonitor/main.js:22:29)
    at PowerMonitor.emit (events.js:210:5)
```

**Comment by ctheune** [comment]
Just happened to me when I moved my MacBook from power and back. Here's the full screenshot:

<img width="526" alt="Screenshot 2020-04-03 at 13 02 56" src="https://user-images.githubusercontent.com/1220572/78354129-9b162a80-75ab-11ea-8058-3b25bf5d8138.png">
