### ISSUE TITLE
error in v2021.11.4 under MacOS

### ISSUE THREAD

**Issue by bones78** [freifunkMUC/jitsi-meet-electron#38]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I have updated the app to v2021.11.4. After the update, the following error shows up and the app does not start.
I have deleted the app incl. Library Folder entries and reinstalled the app manually -> same error.
## Current behavior
A JavaScript error occurred in the main process

Uncaught Exception:
Error: dlopen(/Applications/FreifunkMeet.app/Contents/Resources/app-x64.asar.unpacked/node_modules/@jitsi/electron-sdk/build/Release/sourceId2Coordinates.node, 0x0001): tried: '/Applications/FreifunkMeet.app/Contents/Resources/app-x64.asar.unpacked/node_modules/@jitsi/electron-sdk/build/Release/sourceId2Coordinates.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/lib/sourceId2Coordinates.node' (no such file)
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/Applications/FreifunkMeet.app/Contents/Resources/app-x64.asar/node_modules/@jitsi/electron-sdk/node_addons/sourceId2Coordinates/index.js:2:7)
at Module._compile (internal/modules/cjs/loader.js:1078:30)

## Expected Behavior
normal working app

## Possible Solution
---

## Steps to reproduce
install  v2021.11.4.

# Environment details
iMac 2019, MacOS 12.01

**Comment by awlx** [comment]
@csett86 and I are investigating this and stopped the rollout of 2021.11.4 thank you so much for reporting!

**Comment by T0biii** [comment]
Should we revert https://github.com/freifunkMUC/homebrew-freifunkmeet/pull/22 too?

**Comment by csett86** [comment]
Yes @T0biii, please revert.

**Comment by awlx** [comment]
@bones78 this is fixed in https://github.com/freifunkMUC/jitsi-meet-electron/releases/tag/v2021.11.5
